CREATE TABLE IF NOT EXISTS `agent_tasks` (
  `id` varchar(64) NOT NULL,
  `adopt_id` varchar(64) NOT NULL,
  `user_id` int NOT NULL,
  `agent_id` varchar(64) NOT NULL,
  `source_conversation_id` varchar(128) DEFAULT NULL,
  `source_session_id` varchar(160) DEFAULT NULL,
  `source_message_id` varchar(128) DEFAULT NULL,
  `status` enum('pending','running','succeeded','failed','cancelled') NOT NULL DEFAULT 'pending',
  `input` text NOT NULL,
  `result_markdown` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `adapter_protocol` varchar(96) DEFAULT NULL,
  `remote_task_id` varchar(128) DEFAULT NULL,
  `raw_events_json` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_agent_tasks_adopt_status` (`adopt_id`, `status`, `created_at`),
  KEY `idx_agent_tasks_source_conversation` (`source_conversation_id`),
  KEY `idx_agent_tasks_agent_status` (`agent_id`, `status`)
);
