CREATE TABLE IF NOT EXISTS `message_feedback` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `adopt_id` varchar(64) NOT NULL,
  `conversation_id` varchar(128) NOT NULL,
  `message_id` varchar(128) NOT NULL,
  `rating` enum('positive','negative') NOT NULL,
  `reason_codes_json` text DEFAULT NULL,
  `comment` varchar(500) DEFAULT NULL,
  `role_template` varchar(64) DEFAULT NULL,
  `runtime_type` varchar(32) DEFAULT NULL,
  `selected_model_id` varchar(200) DEFAULT NULL,
  `actual_model_id` varchar(200) DEFAULT NULL,
  `skill_ids_json` text DEFAULT NULL,
  `tool_summary_json` text DEFAULT NULL,
  `input_tokens` int DEFAULT NULL,
  `output_tokens` int DEFAULT NULL,
  `duration_ms` int DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_message_feedback_message` (`user_id`, `adopt_id`, `conversation_id`, `message_id`),
  KEY `idx_message_feedback_rating_created` (`rating`, `created_at`),
  KEY `idx_message_feedback_adopt_created` (`adopt_id`, `created_at`),
  KEY `idx_message_feedback_model_rating` (`actual_model_id`, `rating`)
);
