CREATE TABLE IF NOT EXISTS `knowledge_bases` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(64) NOT NULL,
  `owner_user_id` INT NOT NULL,
  `owner_group_id` INT NOT NULL DEFAULT 0,
  `scope` ENUM('personal','role','enterprise') NOT NULL DEFAULT 'personal',
  `is_global` BOOLEAN NOT NULL DEFAULT FALSE,
  `role_template` VARCHAR(64) NULL,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(500) NOT NULL DEFAULT '',
  `status` ENUM('empty','indexing','ready','failed') NOT NULL DEFAULT 'empty',
  `document_count` INT NOT NULL DEFAULT 0,
  `chunk_count` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(1000) NULL,
  `indexed_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_knowledge_bases_public_id` (`public_id`),
  KEY `idx_knowledge_bases_owner_updated` (`owner_user_id`, `updated_at`),
  KEY `idx_knowledge_bases_group_scope` (`owner_group_id`, `scope`, `updated_at`),
  KEY `idx_knowledge_bases_global_scope` (`is_global`, `scope`, `updated_at`),
  KEY `idx_knowledge_bases_role_scope` (`role_template`, `scope`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `knowledge_documents` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(64) NOT NULL,
  `knowledge_base_id` BIGINT NOT NULL,
  `name` VARCHAR(240) NOT NULL,
  `extension` VARCHAR(16) NOT NULL,
  `mime_type` VARCHAR(160) NOT NULL DEFAULT 'application/octet-stream',
  `storage_path` VARCHAR(700) NOT NULL,
  `size_bytes` BIGINT NOT NULL DEFAULT 0,
  `sha256` VARCHAR(64) NOT NULL,
  `status` ENUM('uploaded','indexing','ready','failed') NOT NULL DEFAULT 'uploaded',
  `chunk_count` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(1000) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_knowledge_documents_public_id` (`public_id`),
  KEY `idx_knowledge_documents_base_updated` (`knowledge_base_id`, `updated_at`),
  KEY `idx_knowledge_documents_base_sha` (`knowledge_base_id`, `sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
