CREATE TABLE `enterprise_mcp_call_receipts` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `request_id` varchar(64) NOT NULL,
  `policy_decision_id` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NULL,
  `status` enum('started','completed','failed','blocked') NOT NULL DEFAULT 'started',
  `server_id` varchar(128) NOT NULL,
  `tool_name` varchar(256) NOT NULL,
  `user_id` int NOT NULL,
  `tenant_id` varchar(80) NOT NULL,
  `adopt_id` varchar(64) NOT NULL,
  `role_key` varchar(64) NOT NULL,
  `identity_mode` enum('platform','tenant','user') NOT NULL,
  `args_hash` varchar(64) NOT NULL,
  `result_hash` varchar(64) NULL,
  `external_request_id` varchar(128) NULL,
  `duration_ms` int NULL,
  `error_code` varchar(128) NULL,
  `started_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_mcp_call_request` (`request_id`),
  UNIQUE KEY `uk_enterprise_mcp_call_idempotency` (`adopt_id`, `server_id`, `tool_name`, `idempotency_key`),
  KEY `idx_enterprise_mcp_call_actor_started` (`user_id`, `started_at`),
  KEY `idx_enterprise_mcp_call_server_started` (`server_id`, `started_at`),
  KEY `idx_enterprise_mcp_call_status_started` (`status`, `started_at`)
);
