CREATE TABLE IF NOT EXISTS `governance_approvals` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `approval_id` varchar(64) NOT NULL,
  `active_binding_key` varchar(64) DEFAULT NULL,
  `status` enum('pending','approved','rejected','consumed','expired') NOT NULL DEFAULT 'pending',
  `policy_decision_id` varchar(64) NOT NULL,
  `policy_code` varchar(128) NOT NULL,
  `rule_version` varchar(64) NOT NULL,
  `principal_fingerprint` varchar(64) NOT NULL,
  `user_id` int NOT NULL,
  `adopt_id` varchar(64) NOT NULL,
  `capability_id` varchar(128) NOT NULL,
  `operation` varchar(256) NOT NULL,
  `resource` varchar(512) DEFAULT NULL,
  `payload_hash` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `reason` text NOT NULL,
  `decision_reason` text DEFAULT NULL,
  `expires_at` timestamp NOT NULL,
  `decided_by` int DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejected_at` timestamp NULL DEFAULT NULL,
  `consumed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_governance_approval_id` (`approval_id`),
  UNIQUE KEY `uk_governance_approval_active_binding` (`active_binding_key`),
  KEY `idx_governance_approval_actor_status` (`user_id`,`adopt_id`,`status`),
  KEY `idx_governance_approval_expiry_status` (`expires_at`,`status`),
  KEY `idx_governance_approval_policy_decision` (`policy_decision_id`)
);
