CREATE TABLE IF NOT EXISTS `a2a_capability_intent_executions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `execution_id` varchar(64) NOT NULL,
  `task_id` varchar(64) NOT NULL,
  `intent_id` varchar(128) NOT NULL,
  `intent_fingerprint` varchar(64) NOT NULL,
  `user_id` int NOT NULL,
  `adopt_id` varchar(64) NOT NULL,
  `source_agent_id` varchar(64) NOT NULL,
  `capability_id` varchar(128) NOT NULL,
  `operation` varchar(128) NOT NULL,
  `side_effect` enum('workspace_write','write','external_send','financial_action','approval_action','admin_action') NOT NULL,
  `binding_id` varchar(128) NOT NULL,
  `binding_version` varchar(64) NOT NULL,
  `target_server_id` varchar(128) NOT NULL,
  `target_tool_name` varchar(256) NOT NULL,
  `payload_hash` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `approval_id` varchar(64) NULL,
  `status` enum('pending','approval_required','executing','succeeded','failed','blocked') NOT NULL DEFAULT 'pending',
  `result_hash` varchar(64) NULL,
  `external_request_id` varchar(128) NULL,
  `error_code` varchar(128) NULL,
  `error_message` text NULL,
  `completed_at` timestamp NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a2a_intent_execution_id` (`execution_id`),
  UNIQUE KEY `uk_a2a_intent_execution_task_intent` (`task_id`,`intent_id`),
  KEY `idx_a2a_intent_execution_actor_status` (`user_id`,`adopt_id`,`status`),
  KEY `idx_a2a_intent_execution_approval` (`approval_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
