CREATE TABLE IF NOT EXISTS `enterprise_asset_sources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `source_id` varchar(128) NOT NULL,
  `display_name` varchar(200) NOT NULL,
  `source_type` enum('document_repository','business_system','rule_catalog','workflow_catalog','capability_service','identity_directory') NOT NULL,
  `source_uri` varchar(1000) NULL,
  `owner_department` varchar(200) NOT NULL,
  `owner_contact` varchar(200) NULL,
  `sync_mode` enum('manual','scheduled','webhook') NOT NULL DEFAULT 'manual',
  `status` enum('active','paused','disabled') NOT NULL DEFAULT 'active',
  `last_sync_at` timestamp NULL,
  `created_by` varchar(128) NOT NULL,
  `updated_by` varchar(128) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_asset_sources_public_id` (`source_id`),
  KEY `idx_enterprise_asset_sources_status_type` (`status`,`source_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS `enterprise_asset_candidates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `candidate_id` varchar(64) NOT NULL,
  `source_id` varchar(128) NOT NULL,
  `enterprise_asset_id` varchar(128) NOT NULL,
  `asset_type` enum('knowledge_document','business_data','policy','skill','mcp_capability','role_identity') NOT NULL,
  `display_name` varchar(240) NOT NULL,
  `source_uri` varchar(1000) NULL,
  `source_version` varchar(64) NOT NULL DEFAULT '1.0',
  `checksum` varchar(64) NOT NULL,
  `suggested_metadata_json` json NOT NULL,
  `confirmed_metadata_json` json NULL,
  `status` enum('draft','review_pending','approved','rejected','published','stale') NOT NULL DEFAULT 'draft',
  `target_asset_type` enum('knowledge_document','enterprise_mcp','skill','policy','role') NULL,
  `target_asset_id` varchar(128) NULL,
  `impact_analysis_json` json NULL,
  `review_note` text NULL,
  `reviewed_by` varchar(128) NULL,
  `reviewed_at` timestamp NULL,
  `published_by` varchar(128) NULL,
  `published_at` timestamp NULL,
  `created_by` varchar(128) NOT NULL,
  `updated_by` varchar(128) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_asset_candidates_public_id` (`candidate_id`),
  UNIQUE KEY `uk_enterprise_asset_candidates_source_asset_version` (`source_id`,`enterprise_asset_id`,`source_version`),
  KEY `idx_enterprise_asset_candidates_source_status` (`source_id`,`status`),
  KEY `idx_enterprise_asset_candidates_asset_status` (`asset_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
