CREATE TABLE IF NOT EXISTS `runtime_agent_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `binding_id` varchar(64) NOT NULL,
  `adoption_id` varchar(64) NOT NULL,
  `runtime_profile` enum('standalone','enterprise_canary','enterprise') NOT NULL,
  `fallback_profile` enum('standalone') NOT NULL DEFAULT 'standalone',
  `gateway_target` varchar(64) NOT NULL,
  `runtime_group_id` varchar(96) NOT NULL,
  `runtime_bot_id` varchar(96) NOT NULL,
  `runtime_user_id` varchar(128) NOT NULL,
  `service_id` varchar(96) NOT NULL,
  `runtime_agent_id` varchar(128) NOT NULL,
  `workspace_key` varchar(128) NOT NULL,
  `asset_set_fingerprint` varchar(64) NULL,
  `binding_version` int NOT NULL DEFAULT 1,
  `status` enum('pending','ready','degraded','disabled') NOT NULL DEFAULT 'pending',
  `validated_at` timestamp NULL,
  `last_error` text NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_runtime_agent_bindings_public_id` (`binding_id`),
  UNIQUE KEY `uk_runtime_agent_bindings_adoption` (`adoption_id`),
  KEY `idx_runtime_agent_bindings_profile_status` (`runtime_profile`,`status`),
  KEY `idx_runtime_agent_bindings_service` (`gateway_target`,`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
